# permissions for end users to edit ipwhitelistconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - ingress.security.moulick
    resources:
      - ipwhitelistconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ingress.security.moulick
    resources:
      - ipwhitelistconfigs/status
    verbs:
      - get
