# permissions for end users to edit ipwhitelistconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipwhitelistconfig-editor-role
rules:
  - apiGroups:
      - ingress.security.moulick
    resources:
      - ipwhitelistconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ingress.security.moulick
    resources:
      - ipwhitelistconfigs/status
    verbs:
      - get
