---
name: Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref || github.run_id }}
  cancel-in-progress: true

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - master

permissions:
  contents: read # for actions/checkout to fetch code
  security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

jobs:
  yamllint:
    name: Run yamllint
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - id: yaml-lint
        name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yaml

      - id: yaml-lint-output
        name: yaml-lint output
        run: echo ${{ steps.yaml-lint.outputs.logfile }}

  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
