name: ginkgo

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ginkgo:
    runs-on: ubuntu-latest
    name: Run test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
          cache: true
      - run: go mod tidy && git diff --exit-code go.mod go.sum
      - run: make generate manifests && git diff --exit-code api/ config/ pkg/
      - run: make envtest
      - run: make test COVER_FILE=cover.out
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cover.out
